name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build binaries
      run: |
        # Create dist directory
        mkdir -p dist
        
        # Build for different platforms (using npm-style naming, these are downloaded and packed into the codevideo-mcp package)
        GOOS=windows GOARCH=amd64 go build -o dist/codevideo-cli-win32-x64.exe .
        GOOS=windows GOARCH=arm64 go build -o dist/codevideo-cli-win32-arm64.exe .
        GOOS=linux GOARCH=amd64 go build -o dist/codevideo-cli-linux-x64 .
        GOOS=linux GOARCH=arm64 go build -o dist/codevideo-cli-linux-arm64 .
        GOOS=darwin GOARCH=amd64 go build -o dist/codevideo-cli-darwin-x64 .
        GOOS=darwin GOARCH=arm64 go build -o dist/codevideo-cli-darwin-arm64 .
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}